### ISSUE TITLE
cant call right click

### ISSUE THREAD

**Issue by madcat820** [pixeltris/GK6X#11]
I have the following script below, It seems im missing something on how to DO a "Right Click" , remapping left alt as right click and remapping space to a macro seems doesn't do anything. Man, thanks for all of these. 

[FnLayer1]
D1:F1
D3:F3
-:F11
RShift:End
A:Macro(MyMacro1)

[Layer1]
Space:Macro(MyMacro3)
RShift:Home
LAlt:MouseRClick	

[Layer3]
A:W
D1:Esc

	[Macro(MyMacro1,0,PressKeyAgainToStop)]
	Down:W:9000

	[Macro(MyMacro3,0,RepeatXTimes,2)]
	Press:MouseRClick

**Comment by madcat820** [comment]
Hey Man, Can you teach mo how to do a "Click" on the script ?

**Comment by pixeltris** [comment]
I haven't been around my keyboard for a while. Hopefully I'll have time to look at this tonight.

**Comment by madcat820** [comment]
howdy.

**Comment by pixeltris** [comment]
So I've had a quick look at this. It works for me on my keyboard (GK84). It's likely that the mouse key values are incorrect in the data files for your keyboard. It has been a while since I updated the data files, so I need to do that at some point.

You can read this issue to see how someone solved a similar issue for their keyboard https://github.com/pixeltris/GK6X/issues/10#issuecomment-568631750

What keyboard are you using?

**Comment by madcat820** [comment]
HeyMan, thanks a lot,
Awesome, will check that out
Im using GK64

**Comment by pixeltris** [comment]
Closing this as right click does work for keyboard which support it. The data files have been updated, so this might now work for you? Feel free to re-open the issue if needed.
