### ISSUE TITLE
Add more user-friendly installation instructions!

### ISSUE THREAD

**Issue by zachcta** [pixeltris/GK6X#118]
Hey, some users may be confused by what you mean by just simply "run with mono" to run the software as I personally have never encountered a project that uses it.
Something like this may make it easier for people to use:

1. Install mono-runtime or whatever the package name is on your distribution 
2. Download the latest release
3. cd into the directory with the executable and run "sudo mono GK6X.exe"

Either this or an install script for Ubuntu or other popular distributions.

**Comment by pixeltris** [comment]
Yea, some improvements could be made there.

The README links to #4 which gives a pretty good overview of how to compile / run on Linux/Mac. Mono distribution wise it's varied as can be seen on the official site https://www.mono-project.com/download/stable/#download-lin

I'll most likely be making Linux/Mac bundles which includes an embedded .NET Core (or Mono depending which results in a small download size) as mentioned in #85. Unfortunately I haven't had the time to finish that yet...

I don't have any plans to write an install script, but a PR which achieves this would be welcomed.

**Comment by holleywood330** [comment]
I tried to do this , knowing it wasn't gonna be easy at all. I have 1 year of knowledge from a high school class that I also failed . so Im not looking at what would be moon runes . but I felt after reading around I could find a good guide on how to install this but their isn't . like at all ,a person that knows even as much as I do would be lost as well . it could just be me but I sat here for almost 3 hours trying to get the .sln file to even build but it wouldn't . it would find the file . you can type the code but if people don't know how to use it properly then know will use it at all . like thanks I know typing code isn't all that fun but damn .u are just as bad as the people who made it . they made it in a lang people can't reed , you are doing the same thing .

**Comment by pixeltris** [comment]
Yea, as mentioned this project could do with improvements in terms of installation and instructions on usage. It's definitely far from user friendly, and I'm sorry you've struggled with getting it to work.

Be sure to check out the official software on [Windows](http://www.jikedingzhi.com/downloadlist?driverID=41) / [Mac](http://www.jikedingzhi.com/downloadlist?driverID=90) if you're on one of those platforms as that's definitely the most straight forward thing to use. You could try the official software under [Wine](https://www.winehq.org/) if you're on Linux, but I'm not sure if it works.

You don't have to build the sln as there's compiled binaries [here](https://github.com/pixeltris/GK6X/releases), but you still need mono to run those binaries (if you're on Linux/Mac).

**Comment by holleywood330** [comment]
thank you for commenting so fast, im on a Mac . I have downloaded mono and as far as I know all the correct files but like I don't know what to do from there. like i don't expect a step by step grind on how to do something like this , or it could be a video of someone doing like that u know.

**Comment by pixeltris** [comment]
I'd definitely recommend using the official software as linked above (which comes as a dmg which you can just install).

If you still want to use the software in this repo, you should be able to download a release build https://github.com/pixeltris/GK6X/releases then unzip the folder, open a [terminal](https://en.wikipedia.org/wiki/Terminal_(macOS)) in the `build` directory of the unzipped folder (or `cd` into there), and then run `sudo mono GK6X.exe`.

Unfortunately I'm not in the position to make a video of this, which might be frustruating for you, but again I'd definitely recommend using the official software which should be much more straight forward http://www.jikedingzhi.com/downloadlist?driverID=90

**Comment by holleywood330** [comment]
im not trying to be difficult by any means. I just want others who are trying to do download this software for their keyboards , that they have the opportunity to do .im complaining about this, cause its amazing that you have taken the time out of your day to code this stuff like , holy man respects to you. im just saying it won't go that far if people don't know how to use it . I have installed and uninstalled the software from this http://www.jikedingzhi.com/downloadlist?driverID=90 website all ready, I get the "this device isn't supported" message and nothing has fixed it .
<img width="1440" alt="Screen Shot 2021-05-17 at 5 14 00 PM" src="https://user-images.githubusercontent.com/84345922/118562992-61fb3400-b733-11eb-8996-de3c244507b0.png">n  this is what im looking at . It won't find the file at all. its up too you if your gonna help me, ill eventually find out hopefully. I don't mind if you don't want to help . but I right click on the build file from "GK6X-GK6X-v1.14 2 ". it sends me to a terminal like u said . I then paste "sudo mono GK6X.exe " after it tells me to enter a my password I do then it tells me "no such file or directory. what do I do

**Comment by holleywood330** [comment]
I’m dumb , I got it too run but like now what how do I get into the actual program

**Comment by holleywood330** [comment]
I went at it again I actually got it to build this time , its just that it won't recognize my keyboard at all. one I run the .exe file it just hangs . it doesn't say anything as you said it would until it found a keyboard to connect to . the thing is I tried 4 different usb cables and I tried every port and nothing got the keyboard to be read. on my Mac its says that is a GK61 keyboard but the official software didn't read my device either, so I don't know if I got a fake keyboard. I got mine of amazon. is their any work around to this ?

**Comment by pixeltris** [comment]
It could be that there's a fault in the hardware which is causing the expected communication to fail. Unfortunately there's no good way to determine this without using tricky tools like Wireshark's USB sniffer.

Your best bet would be to talk to your supplier, mentioning your issue, and look at getting a replacement.

**Comment by holleywood330** [comment]
well I might have to look into using the Wireshark's sniffer, but Its really hard to point out the issue . cause I got mine off amazon and when I go to the Usb Bus its connected to its says GK61 Gaming Keyboard, but their isn't a manufacturer so it could be fake and that's why the software isn't picking it up Maybe.

 It could also be the connection , im using the cable that came with the keyboard rn and the apple dongle to connect it so their shouldn't be an issue , unless its with the dongle .at that point I would just use the Wireshark to figure it out.also if you don't mind expelling , why does your code work for people that get the "not supported device" how does yours find the keyboard but the official software can't 

is their anyway for me to check the status of the keyboard without having to use any third party software , also their is a shit ton of code for this . did you write most of this by your self and if so why. not only how did you go about writing it and knowing it would work for the most part. also how did you go about learning programing , cause I might pick it up but I don't know how I would without school.

**Comment by pixeltris** [comment]
For Wireshark you'd need to know the [HID protocol](https://en.wikipedia.org/wiki/Human_interface_device) to know what to look for. Wireshark is a low level tool for inspecting packets (essentially a sequence of raw numbers).

I imagine the connection is fine, otherwise you wouldn't be able to use the keybord at all. I assume there's some hardware fault, or your device isn't actually a GK61.

The official software should have the same compatibility as the software in this project. As with any software there are many issues which may prevent this software or the official software working for some people.

You might be able to use a tool to find out your product/vendor ID of your keyboard. That would tell you if it's compatible with the software. The software only looks for the following product / vendor id:

https://github.com/pixeltris/GK6X/blob/6ef1a8012beeb5fdd891906a6569bd0fc3209d75/GK6X/KeyboardDeviceManager.cs#L15-L23

There isn't very much code in this project. The project was made as I wanted to see if there was additional functionality in the communication protocol to remove any limitations in the official software. I reverse engineered the official software with IDA Pro and with help from annotations of firmware disassembly here https://github.com/wgwoods/gk64-python. Any piece of software can be reverse engineered / re-implemented to varying degrees with enough effort. I learnt programming myself very slowly over many years and struggled to get started. I always had a goal which helped (e.g. making a small game, tool, etc). There are many resources online these days which are great for learning how to code.

**Comment by holleywood330** [comment]
yea it says the vendor id 0x32e3 and the product id is 0x00f7 , is their an easier way to check the keyboards usb connection using Microsoft instead of a Mac. also if this is a fake then what should I do cause I only use the keyboard on ps4 so the software doesn't even matter , I would just like to just have fin with it . like is their no way for me to acutely get into the software to change the lighting or am I just stuck with the basic .

**Comment by pixeltris** [comment]
Nothing really comes up when searching that vendorid online. But yea that isn't a GK6X keyboard. Possibly a company is doing some weird things and taking advantage of the GK6X brand name? The only thing I can suggest is to contact Amazon to ask for a refund, then buy it again from a different source.

I'm going to clean up these comments some-when soon to keep this issue relevant to its original purpose.

**Comment by holleywood330** [comment]
I looked at the product page for the keyboard on Amazon . when I checked it does say its sent from Hk them selfs, but they send it too a 3rd party distributor that then send i too me. so idk what is happening with the 3rd party service cause when I go to the HK Gaming official site it sends you to the same link I got my keyboard from. it suck that it is fake but the only real problem is that u can't use the software . the keyboard is also out of the refund dates so I don't think I can do anything about that. Thanks for helping me out tho , appreciate it a lot

**Comment by pixeltris** [comment]
I've gone ahead and cleaned up comments which weren't super relevant to this, or the project in general as previously mentioned.

In https://github.com/pixeltris/GK6X/commit/96e9c041778c9370f9bf06000d687f4873fbb468 I added more verbose instructions on how to get mono working (linking to the mono downloads page, as well as mentioning the `mono-complete` package which should be on most distros). I've also included more info on general program usage.

Perhaps still not super use-friendly instructions, and now a little bit wordy. But hopefully it's a little more clear than it was.

Going to close this. Feel free to reopen if you think more could be done.
