### ISSUE TITLE
Arrow keys!

### ISSUE THREAD

**Issue by emandrael** [pixeltris/GK6X#121]
Hello, I might be an idiot and just haven't seen it. But I don't think the arrow keys show up when you use the dumpkeys function on the program.

Thank you for this program!

**Comment by pixeltris** [comment]
`dumpkeys` is used to find the key names for the keys on your keyboard. It's just a quick reference really, and doesn't show how the keys are currently mapped (just their default names). Some keyboards the `dumpkeys` command doesn't work so well due to the weak physical key positioning check (it attempts to log the keys in order, but can fail).

I'm not sure why the arrow keys wouldn't show up, but it could be that the data files are incorrect?

**Comment by iapicca** [comment]
@pixeltris 
I've never used mono before, how do I compile this on linux (ubuntu 20.04)?

**Comment by pixeltris** [comment]
Not sure if you solved this. Arrows should definitely work and can be found in the DriverValue list. If the issue persists feel free to reopen this issue.

https://github.com/pixeltris/GK6X/blob/96e9c041778c9370f9bf06000d687f4873fbb468/GK6X/KeyValues.cs#L269
