### ISSUE TITLE
Gk6x software!

### ISSUE THREAD

**Issue by bannix666** [pixeltris/GK6X#155]
Hello, a new version of the software V6.0.0.**48** has been released on the jikedingzhi website. Please provide a changelog, as the original site is not fully functional.

**Comment by pixeltris** [comment]
Yea their website has been in maintenance mode for a little while now. I might update the readme to link to the main page as there isn't any clear indication when their "maintenance" will end.

I'm not sure what you mean by changelog. They never provided changelogs for any releases as far as I know. Typically the updates are just data files for new / upcoming products. I don't think the functionality has changed since 6.0.

I'll update to the latest data files when I get the chance.

**Comment by bannix666** [comment]
> Я обновлю файлы данных до последних версий, когда у меня будет возможность.

Okey, Thank you =)
