### ISSUE TITLE
Why are GUI sources not included into the repository? 

### ISSUE THREAD

**Issue by maximka777** [pixeltris/GK6X#178]
It would be nice to have access to GUI sources to do possible fixes in it.

Is GUI module a separate project? It would be nice to add a link to it or explain where it comes from.

Maybe GUI is extracted from official software?

**Comment by pixeltris** [comment]
As roughly mentioned in https://github.com/pixeltris/GK6X/pull/179 the file [updating.txt](https://github.com/pixeltris/GK6X/blob/master/Build/Data/Updating.txt) describes how these GUI files are updated (but needs improvements).

They are obtained from the official software under `GK6XPlus Driver/CMSEngine/driver/`. The command `update_data` is used to extract the important files and dump them into `Build/Data`. Additionally it merges multiple versions of the `driver` software and produces the final `driver` folder which is zipped up into a release. This is because some versions of the GK6X software is special to a given product line (e.g. `Tronsmart Radiant` keyboards).

The GUI data isn't included in the repo itself (only as releases) as these files aren't necessary to map keyboards using the CLI and the additional files would bloat the repo with 60+ MB of unused data.
