### ISSUE TITLE
Gui is kind of broke

### ISSUE THREAD

**Issue by razzor1984** [pixeltris/GK6X#181]
Hello,

after starting the gui via comand prompt -  gk6x.exe /gui

i cant edit under Primary my sk21 keyboard:

![grafik](https://user-images.githubusercontent.com/3404263/146503324-cf0ae582-5029-4579-ab59-76bf91eb9aa8.png)

I cant klick on the configuration Buttons or anything there i only getting the stop sign.

Os information window 10 - 21h2
Tested Browser:Version 95.0.4638.54 (Official Build) (64-bit)
Edge: Current stabel build
FF:95.0.1 (64-Bit)

Best Regards Razzor

**Comment by pixeltris** [comment]
You need to resize your browser. The original software was built on a fixed size / aspect ratio. The buttons on your screenshot are being blocked off due to being pushed under the keyboard buttons (which are blocked off on the base layer). Resizing should fix it.

See https://github.com/pixeltris/GK6X/issues/65 https://github.com/pixeltris/GK6X/issues/144 https://github.com/pixeltris/GK6X/issues/165

**Comment by razzor1984** [comment]
Thanks, it fixed it, I have an additional question, how can I store the lightning settings permanent. After applying the RGB it only shows it for a short period of time. After that I must start the Program again and load the RGB on the device.

**Comment by pixeltris** [comment]
Lighting should be permanent. You should have a lighting key combo on your keyboard that lets you cycle through your assigned lighting settings. Some keyboard are slightly different though.

Some things with the GUI are kinda weird where you need to "apply" and "save" things, which is why it might be temporary if you aren't doing both.

**Comment by razzor1984** [comment]
Thanks that’s what i needed, i googled it and for the Epomaker sk21 its FN + 1 that’s the mode which is the static lightmode.
