### ISSUE TITLE
Using .le files from Official Client

### ISSUE THREAD

**Issue by ecliptick** [pixeltris/GK6X#62]
Wondering how you managed to convert the garbage characters from the original client to the .json ones you currently have?
Assuming I want to edit lighting effects using the official GUI and save the .le file and use that file with GK6X, how do I do it? Currently .le files created by the official client comes out as garbage characters.

**Comment by pixeltris** [comment]
So the lighting effect files (and macro files) are encrypted with a basic form of encryption. I don't think I've added the ability to automatically decrypt the files you create. There is a way you can do it but it's a little bit of work:

1) Navigate to `%appdata%\GK6XPlus-CMS\Account\0\LE`
2) Copy all of the files to `C:\Program Files (x86)\GK6XPlus Driver\CMSEngine\driver\res\data\le`
3) Open the GK6X.exe and run the command `update_data C:\Program Files (x86)\GK6XPlus Driver\CMSEngine\driver`

Your lighting effect files should now be extracted and available to be used by the GK6X.exe tool.

**Comment by ecliptick** [comment]
nice ! will try it out. BTW, any chance of releasing the full list of usable commands?

**Comment by pixeltris** [comment]
The code for the commands can be found here:

https://github.com/pixeltris/GK6X/blob/ec8878bcf97a0da518318fde1f85456823a2f783/GK6X/Program.cs#L97

Oh it actually looks like I wrote a command to export the user made lighting files made via the web gui. `gui_le`. Though it isn't set up to copy the ones made in the official software at the moment.

All of the commands listed there:

- `map` - maps the keys / lighting / macros
- `unmap` - resets the keyboard data to the default values (as defined by the files)
- `dumpkeys` - prints out the keys on your keyboard (as seen by the data files)
- `findkeys` - prints out keys as you press them (useful for finding keys not mapped in the data files)
- `update_data` - used to update data files for this repo based on updated official software data files
- `gui` - opens a web gui
- `gui_le` - copies the web gui lighting files so that the `map` command can use them

**Comment by kypi** [comment]
This didn't work when I tried to run it. Got an error: "Couldn't find formatted JS files to process!"

**Comment by pixeltris** [comment]
`update_data` does a full update of all files from the official software (and doesn't copy over any user made lighting data), that command requires formatted JS files.

`gui_le` is what copies user made lighting effect files, and it shouldn't require JS formatted files.
