### ISSUE TITLE
Cannot map keys?

### ISSUE THREAD

**Issue by hongfeiyang** [pixeltris/GK6X#7]
Hi pixeltris,

First I must appreciate the time and effort you have spent on creating such a useful tool for us. I tried to compiled the code on Visual Studio for Mac, and tried put this in my_model.txt file under /UserData:

[Base,Layer1,Layer2,Layer3,FnLayer1,FnLayer2,FnLayer3]
Pause:Delete

and while the program was running, I entered map, and then dumped the keys, but I still see nothing changed. What is going on? Did I do anything wrong?

I have a GK84 Keyboard wired to my MacBook Pro running Catalina 10.15.2.

**Comment by pixeltris** [comment]
The dump key command actually just lists the names of your keys in the order that they appear on your keyboard (so that you can get the names to map the keys between each other). It doesn't say the name of the key that you mapped it to (the keyboard doesn't ever actually send that information to the PC).

Saving the file and using the `map` command should be enough for the mapping to work. Try pressing the mapped key after using the `map` command. There currently isn't any error notification if it fails so you might have to try `map` a couple more times.

**Comment by chent7** [comment]
Hey pixeltris!
I have the GK84, and I noticed that the delete key on the keyboard (the one above the right arrow key) is unmappable. This is what I had:

[Base,Layer1,Layer2,Layer3,FnLayer1,FnLayer2,FnLayer3]
Delete:Home

Just to note I also had remapped a key to delete just a few lines above it:

[Base,Layer1,Layer2,Layer3,FnLayer1,FnLayer2,FnLayer3]
Pause:Delete

Maybe this is why the key is unmappable??

**Comment by pixeltris** [comment]
You could try putting no other mappings other than "Delete:Home" and see if that works. If it doesn't then it's likely something is off in the data files. I really need to update the data files... it's been months.

**Comment by chent7** [comment]
Can confirm the delete key is indeed unmappable even by itself. 

Thank you for your hard work, I would hate to have the driver software constantly runnning.

**Comment by pixeltris** [comment]
It's likely your keyboard has a different index mapping for your delete key. It should just be a matter of finding the correct index. See the following comment on how to locate the index, and how @khaledose managed to fix the index mapping for one of their keys.

I should probably make something that can aid with finding unmapped keys as it's currently a very manual process. With some additional code it might be possible to use the 'driver' layer and map all possible indexes to macros to create callbacks at a software level to identify keys.

https://github.com/pixeltris/GK6X/issues/10#issuecomment-568420743

**Comment by chent7** [comment]
Thanks for the information. I bought the keyboard specifically for modding it into a different case and adding rgb underglow. Yesterday when I took the keyboard apart to look at the screw holes and the stablizers, I saw 2 unsoldered rgb headers. So I took a spare rgb strip I had and did some testing and they worked. Hopefully with some testing I can figure out how they are mapped in the le files and in the firmware. At the moment it looks like they are mapped to the lighting on the next closest key.

**Comment by pixeltris** [comment]
https://github.com/pixeltris/GK6X/commit/b6105c40c37cc1004cbb0c64a877ed39fe06ab73 since this commit it's possible to find unmappable keys using the 'findkeys' command. You type the command (heed the warning) and then press the key that's unmappable. It will tell you the index of the key so that you can add it to the data files.
