### ISSUE TITLE
Mapping Mac Keys?

### ISSUE THREAD

**Issue by JusJae** [pixeltris/GK6X#75]
Is there a way to change the LWin and LAlt to LCmd and LOpt because I am not getting how this software is supposed to work. I have tried it on tyhe Gui version and the CLi version and i dont get it.

**Comment by pixeltris** [comment]
Aren't those keys essentially flipped for MacOS. So yea you'd essentially want to just flip where LWin / LAlt are. I'm afraid I can't help much more than what is provided because I would just be re-iterating what is already written.

For the GUI I'd recommend youtubing a tutorial for using the gui similar keyboards such as GK64.
